### PR TITLE
Update README.md to include an easier to understand explanation for u…

### PR DESCRIPTION
**Pull request by codestack-rmf**
…ser.

### CODE REVIEW

**Comment by jochenchrist** [comment]
Thanks for your contribution.
I think it might be a good idea to introduce an FAQ section.

I'd put the FAQ after the actual specification, to save some safe on the top, as the first example is quite powerful.

**Comment by simonharrer** [comment]
@codestack-rmf still interested in contributing the FAQ? Otherwise, I'd close this.

**Comment by jochenchrist** [comment]
This PR is stuck.
I would close this PR if there is no progress until 30. April 2024.

**Comment by jochenchrist** [comment]
Nevertheless, thank you for your contribution.
Also feel free to join the community in https://datacontract.com/slack

**Pull request closed without merging**
